name: "HA Remote S.M.A.R.T."
version: "1.0.4"
slug: "ha_remote_smart"
description: "Reads SMART data from storage devices and publishes it to MQTT"
url: "https://github.com/Aculeasis/ha_remote_smart/tree/main/ha_remote_smart"
image: "ghcr.io/aculeasis/ha_remote_smart-{arch}"
arch:
  - armv7
  - aarch64
  - amd64
startup: "application"
boot: "auto"
init: false
apparmor: true
udev: true
full_access: true

privileged:
  - SYS_RAWIO
  - SYS_ADMIN
  - DAC_READ_SEARCH

services:
  - "mqtt:need"

options:
  mqtt_auto: true
  mqtt:
    host: "core-mosquitto"
    port: 1883
    username: ""
    password: ""
  update_interval: 600
  missing_attribute: false
  devices:
    - device: sda
      id: sda
      name: "ULOCAL SSD (/)-250GB"
schema:
  mqtt_auto: bool
  mqtt:
    host: str
    port: port
    username: str
    password: str
  update_interval: int
  missing_attribute: bool
  devices:
    - device: str
      id: str
      name: str?
      cmd: str?
